#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ImpeltechTime.Droid.Resource", IsApplication=true)]

namespace ImpeltechTime.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int orange = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int orange2 = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int yellow = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Checked_Checkbox_2_104 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Checked_Checkbox_2_48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Checked_Checkbox_2_96 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Checked_Checkbox_52 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Checkmark_104 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Cloud_Checked_48 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Cloud_Checked_80 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Cloud_Checked_96 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Collapse_Arrow_48_down = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Collapse_Arrow_48_left = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Collapse_Arrow_48_right = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Collapse_Arrow_48_up = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Error_80 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_pause = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_play = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int login_screen_gradient_shape = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Menu_2_48 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Menu_2_48_2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Menu_2_96 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Menu_2_96_2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pause = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int play_arrow_48px = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int LoginButton = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int appNameTextView = 2131165186;
			
			// aapt resource value: 0x7f070019
			public const int contentLayout = 2131165209;
			
			// aapt resource value: 0x7f07000a
			public const int controlPanelLayout = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int currentDateTextView = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int footerLayout = 2131165202;
			
			// aapt resource value: 0x7f070018
			public const int fullContentLayout = 2131165208;
			
			// aapt resource value: 0x7f070007
			public const int headerLayout = 2131165191;
			
			// aapt resource value: 0x7f070011
			public const int listLayout = 2131165201;
			
			// aapt resource value: 0x7f070003
			public const int loginEditText = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int loginLayout = 2131165185;
			
			// aapt resource value: 0x7f070006
			public const int logoutItem = 2131165190;
			
			// aapt resource value: 0x7f070000
			public const int mainLayout = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int menuButton = 2131165193;
			
			// aapt resource value: 0x7f07000d
			public const int nextDateButton = 2131165197;
			
			// aapt resource value: 0x7f070004
			public const int passwordEditText = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int plannedWorklogTextView = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int previousDateButton = 2131165196;
			
			// aapt resource value: 0x7f07001d
			public const int remainingTimeTextView = 2131165213;
			
			// aapt resource value: 0x7f070016
			public const int sendAllWorklogButton = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int sendStatusImageButton = 2131165205;
			
			// aapt resource value: 0x7f07001e
			public const int sendWorklogButton = 2131165214;
			
			// aapt resource value: 0x7f070010
			public const int sentWorklogTextView = 2131165200;
			
			// aapt resource value: 0x7f070014
			public const int separator = 2131165204;
			
			// aapt resource value: 0x7f070017
			public const int taskLoggingStateButton = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int taskSubjectTextView = 2131165211;
			
			// aapt resource value: 0x7f070013
			public const int tasksListView = 2131165203;
			
			// aapt resource value: 0x7f07001c
			public const int tillDateTextView = 2131165212;
			
			// aapt resource value: 0x7f07000e
			public const int timeInfoLayout = 2131165198;
			
			// aapt resource value: 0x7f070008
			public const int timerChronometer = 2131165192;
			
			// aapt resource value: 0x7f070020
			public const int unaccountedTextView = 2131165216;
			
			// aapt resource value: 0x7f07001a
			public const int unaccountedTimeLayout = 2131165210;
			
			// aapt resource value: 0x7f07001f
			public const int unaccountedWorkTimeTextView = 2131165215;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int main_menu = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskList = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int TaskRowView = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Login = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int LoginHint = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int PasswordHint = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
