#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ImpeltechTime.Droid.Resource", IsApplication=true)]

namespace ImpeltechTime.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040001
			public const int black = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int orange = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int orange2 = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int white = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int yellow = 2130968580;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Cloud_Checked_48 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Cloud_Checked_80 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Cloud_Checked_96 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Collapse_Arrow_48_left = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Collapse_Arrow_48_right = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Error_80 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_launcher = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Icon = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int login_screen_gradient_shape = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Menu_2_48 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Menu_2_48_2 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Menu_2_96 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Menu_2_96_2 = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070014
			public const int LoginButton = 2131165204;
			
			// aapt resource value: 0x7f070011
			public const int appNameTextView = 2131165201;
			
			// aapt resource value: 0x7f07001e
			public const int commentEditText = 2131165214;
			
			// aapt resource value: 0x7f070034
			public const int contentLayout = 2131165236;
			
			// aapt resource value: 0x7f070025
			public const int controlPanelLayout = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int currentDateTextView = 2131165222;
			
			// aapt resource value: 0x7f07001f
			public const int dialogButtonsLayout = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int dialogCancelSendingButton = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int dialogSendWorklogButton = 2131165217;
			
			// aapt resource value: 0x7f070018
			public const int dialogSettingsLayout = 2131165208;
			
			// aapt resource value: 0x7f070005
			public const int dialog_2_ButtonsLayout = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int dialog_2_CancelButton = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int dialog_2_OKButton = 2131165191;
			
			// aapt resource value: 0x7f070001
			public const int dialog_2_SettingsLayout = 2131165185;
			
			// aapt resource value: 0x7f07000b
			public const int dialog_3_CancelButton = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int dialog_3_OKButton = 2131165196;
			
			// aapt resource value: 0x7f070009
			public const int dialog_3_SettingsLayout = 2131165193;
			
			// aapt resource value: 0x7f07002d
			public const int footerLayout = 2131165229;
			
			// aapt resource value: 0x7f070033
			public const int fullContentLayout = 2131165235;
			
			// aapt resource value: 0x7f070022
			public const int headerLayout = 2131165218;
			
			// aapt resource value: 0x7f07002c
			public const int listLayout = 2131165228;
			
			// aapt resource value: 0x7f070012
			public const int loginEditText = 2131165202;
			
			// aapt resource value: 0x7f070010
			public const int loginLayout = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int logoutItem = 2131165205;
			
			// aapt resource value: 0x7f07000f
			public const int mainLayout = 2131165199;
			
			// aapt resource value: 0x7f070024
			public const int menuButton = 2131165220;
			
			// aapt resource value: 0x7f070028
			public const int nextDateButton = 2131165224;
			
			// aapt resource value: 0x7f070013
			public const int passwordEditText = 2131165203;
			
			// aapt resource value: 0x7f07002a
			public const int plannedWorklogTextView = 2131165226;
			
			// aapt resource value: 0x7f070027
			public const int previousDateButton = 2131165223;
			
			// aapt resource value: 0x7f070016
			public const int reloadTasksItem = 2131165206;
			
			// aapt resource value: 0x7f070038
			public const int remainingTimeTextView = 2131165240;
			
			// aapt resource value: 0x7f070031
			public const int sendAllWorklogButton = 2131165233;
			
			// aapt resource value: 0x7f070030
			public const int sendStatusImageButton = 2131165232;
			
			// aapt resource value: 0x7f070039
			public const int sendWorklogButton = 2131165241;
			
			// aapt resource value: 0x7f07002b
			public const int sentWorklogTextView = 2131165227;
			
			// aapt resource value: 0x7f07002f
			public const int separator = 2131165231;
			
			// aapt resource value: 0x7f070002
			public const int spentHours_numberPicker = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int spentMinutes_numberPicker = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int spentSeconds_numberPicker = 2131165188;
			
			// aapt resource value: 0x7f07001a
			public const int spentTimeTextView = 2131165210;
			
			// aapt resource value: 0x7f07000a
			public const int startDatePicker = 2131165194;
			
			// aapt resource value: 0x7f07001c
			public const int startDateTextView = 2131165212;
			
			// aapt resource value: 0x7f070032
			public const int taskLoggingStateButton = 2131165234;
			
			// aapt resource value: 0x7f070036
			public const int taskSubjectTextView = 2131165238;
			
			// aapt resource value: 0x7f07002e
			public const int tasksListView = 2131165230;
			
			// aapt resource value: 0x7f07000e
			public const int textItem = 2131165198;
			
			// aapt resource value: 0x7f07000d
			public const int textViewItem_2 = 2131165197;
			
			// aapt resource value: 0x7f070037
			public const int tillDateTextView = 2131165239;
			
			// aapt resource value: 0x7f070029
			public const int timeInfoLayout = 2131165225;
			
			// aapt resource value: 0x7f070023
			public const int timerChronometer = 2131165219;
			
			// aapt resource value: 0x7f070017
			public const int txt_dia = 2131165207;
			
			// aapt resource value: 0x7f070019
			public const int txt_dia2 = 2131165209;
			
			// aapt resource value: 0x7f07001b
			public const int txt_dia3 = 2131165211;
			
			// aapt resource value: 0x7f07001d
			public const int txt_dia4 = 2131165213;
			
			// aapt resource value: 0x7f070000
			public const int txt_dia_2 = 2131165184;
			
			// aapt resource value: 0x7f070008
			public const int txt_dia_3 = 2131165192;
			
			// aapt resource value: 0x7f07003b
			public const int unaccountedTextView = 2131165243;
			
			// aapt resource value: 0x7f070035
			public const int unaccountedTimeLayout = 2131165237;
			
			// aapt resource value: 0x7f07003a
			public const int unaccountedWorkTimeTextView = 2131165242;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int edit_spent_time = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int edit_start_date = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int listItem_tmp2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ListViewItem_tmp = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Login = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int main_menu = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int sendWorklogDialog = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TaskList = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TaskRowView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int Login = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int LoginHint = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int Password = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int PasswordHint = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CustomActionBarTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyActionBar = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
