#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ImpeltechTime.Droid.Resource", IsApplication=true)]

namespace ImpeltechTime.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Checked_Checkbox_2_104 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Checked_Checkbox_2_48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Checked_Checkbox_2_96 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Checked_Checkbox_52 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Checkmark_104 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Cloud_Checked_48 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Cloud_Checked_80 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Cloud_Checked_96 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Collapse_Arrow_48_down = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int Collapse_Arrow_48_left = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Collapse_Arrow_48_right = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Collapse_Arrow_48_up = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Error_80 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_launcher = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int icon_pause = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int icon_play = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int login_screen_gradient_shape = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int Menu_2_48 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int Menu_2_48_2 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int Menu_2_96 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Menu_2_96_2 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int pause = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int play_arrow_48px = 2130837527;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int LoginButton = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int appNameTextView = 2131034114;
			
			// aapt resource value: 0x7f050018
			public const int contentLayout = 2131034136;
			
			// aapt resource value: 0x7f050009
			public const int controlPanelLayout = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int currentDateTextView = 2131034122;
			
			// aapt resource value: 0x7f050011
			public const int footerLayout = 2131034129;
			
			// aapt resource value: 0x7f050017
			public const int fullContentLayout = 2131034135;
			
			// aapt resource value: 0x7f050006
			public const int headerLayout = 2131034118;
			
			// aapt resource value: 0x7f050010
			public const int listLayout = 2131034128;
			
			// aapt resource value: 0x7f050003
			public const int loginEditText = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int loginLayout = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int mainLayout = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int menuButton = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int nextDateButton = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int passwordEditText = 2131034116;
			
			// aapt resource value: 0x7f05000e
			public const int plannedWorklogTextView = 2131034126;
			
			// aapt resource value: 0x7f05000b
			public const int previousDateButton = 2131034123;
			
			// aapt resource value: 0x7f05001c
			public const int remainingTimeTextView = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int sendAllWorklogButton = 2131034133;
			
			// aapt resource value: 0x7f050014
			public const int sendStatusImageButton = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public const int sendWorklogButton = 2131034141;
			
			// aapt resource value: 0x7f05000f
			public const int sentWorklogTextView = 2131034127;
			
			// aapt resource value: 0x7f050013
			public const int separator = 2131034131;
			
			// aapt resource value: 0x7f050016
			public const int taskLoggingStateButton = 2131034134;
			
			// aapt resource value: 0x7f05001a
			public const int taskSubjectTextView = 2131034138;
			
			// aapt resource value: 0x7f050012
			public const int tasksListView = 2131034130;
			
			// aapt resource value: 0x7f05001b
			public const int tillDateTextView = 2131034139;
			
			// aapt resource value: 0x7f05000d
			public const int timeInfoLayout = 2131034125;
			
			// aapt resource value: 0x7f050007
			public const int timerTextView = 2131034119;
			
			// aapt resource value: 0x7f05001f
			public const int unaccountedTextView = 2131034143;
			
			// aapt resource value: 0x7f050019
			public const int unaccountedTimeLayout = 2131034137;
			
			// aapt resource value: 0x7f05001e
			public const int unaccountedWorkTimeTextView = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int TaskList = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int TaskRowView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int Login = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int LoginHint = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Password = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int PasswordHint = 2130968581;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
